/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jikexueyuan_usingcprintlog_UsingCPrintLog */
//#include <iostream>

#ifndef _Included_com_jikexueyuan_usingcprintlog_UsingCPrintLog
#define _Included_com_jikexueyuan_usingcprintlog_UsingCPrintLog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jikexueyuan_usingcprintlog_UsingCPrintLog
 * Method:    usingCPrintLog
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jikexueyuan_usingcprintlog_UsingCPrintLog_usingCPrintLog
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
