/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#include <iostream>
#include <android/log.h>
/* Header for class com_jikexueyuan_androidclog_UsingCPrintLog */

#ifndef _Included_com_jikexueyuan_androidclog_UsingCPrintLog
#define _Included_com_jikexueyuan_androidclog_UsingCPrintLog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jikexueyuan_androidclog_UsingCPrintLog
 * Method:    usingCPrintLog
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jikexueyuan_androidclog_UsingCPrintLog_usingCPrintLog
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
